asciidoc:
  engine: asciidoctor
asciidoctor:
  :attributes:
    source-highlighter: highlight.js
profiles:
  production:
    base_url: https://weld.cdi-spec.org
    google_analytics: UA-45187401-1
    disqus_generate_id: true
    disqus: weld-cdi
    deploy:
      host: github_pages
      branch: master
  github:
    base_url: https://weld.github.io
    deploy:
      host: github_pages
      branch: master
  development:
    base_url: http://localhost:4242
    disqus: weld-cdi
    disqus_developer: true
title: Weld
